# railway.toml
[build]
builder = "NIXPACKS"

[phases.setup]
aptPkgs = ["ffmpeg"]

[deploy]
startCommand = "node backend/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PORT = "8080"
NODE_ENV = "production"
